# Generated by Django 6.0.7 on 2026-07-17 23:25

import Core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_name', models.CharField(max_length=256, validators=[Core.validators.validator_name])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner', 'directory_name'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=256, upload_to='Images/')),
                ('file_name', models.CharField(max_length=128, validators=[Core.validators.validator_name])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Core.directory')),
            ],
            options={
                'ordering': ['directory', 'file_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_profile', models.ImageField(blank=True, max_length=256, upload_to='ProfileImages/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['directory_name'], name='directory_name'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['created_at'], name='directory_created'),
        ),
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together={('owner', 'directory_name')},
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_name'], name='file_name'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['date'], name='file_date'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('directory', 'file_name')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['image_profile'], name='user_profile_images'),
        ),
    ]
